services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - '3000'
    networks:
      - web
      - apps_default

networks:
  web:
    external: true
  apps_default:
    external: true
